export const NOTIFICATION_TYPES = {
  APPLICATION_SUBMITTED: 'APPLICATION_SUBMITTED',
  APPLICATION_UNDER_REVIEW: 'APPLICATION_UNDER_REVIEW',
  APPLICATION_SHORTLISTED: 'APPLICATION_SHORTLISTED',
  APPLICATION_SELECTED: 'APPLICATION_SELECTED',
  APPLICATION_REJECTED: 'APPLICATION_REJECTED',

  NEW_APPLICATION: 'NEW_APPLICATION',

  NEW_RECRUITER_REGISTRATION: 'NEW_RECRUITER_REGISTRATION',
  RECRUITER_VERIFIED: 'RECRUITER_VERIFIED',
  RECRUITER_REJECTED: 'RECRUITER_REJECTED',
};

export const RELATED_ENTITY_TYPES = {
  APPLICATION: 'APPLICATION',
  JOB: 'JOB',
  RECRUITER: 'RECRUITER',
};

export const APPLICATION_STATUS_NOTIFICATION_TYPE = {
  under_review: NOTIFICATION_TYPES.APPLICATION_UNDER_REVIEW,
  shortlisted: NOTIFICATION_TYPES.APPLICATION_SHORTLISTED,
  selected: NOTIFICATION_TYPES.APPLICATION_SELECTED,
  rejected: NOTIFICATION_TYPES.APPLICATION_REJECTED,
};
