import { useEffect, useRef, useState, useCallback } from 'react';
import { useParams, useNavigate, Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import {
  ArrowLeft,
  MapPin,
  Calendar,
  Briefcase,
  CheckCircle2,
  Sparkles,
  Heart,
  Share2,
  Building2,
  AlertTriangle,
  RefreshCcw,
} from 'lucide-react';
import { Card, CardBody } from '@/components/ui/Card';
import { Badge } from '@/components/ui/Badge';
import { Button } from '@/components/ui/Button';
import { Skeleton, SkeletonText } from '@/components/ui/Skeleton';
import { CompanyLogo } from '@/components/shared/CompanyLogo';
import { JobCard } from '@/features/student/components/JobCard';
import { JobMatchModal } from '@/features/student/components/JobMatchModal';
import { useToast } from '@/hooks/useToast';
import { formatRelativeTime } from '@/utils/formatRelativeTime';
import { parseJobSkills } from '@/utils/parseJobSkills';
import {
  useJobDetails,
  useJobs,
  useMyApplications,
  useJobMatch,
  useGenerateJobMatch,
  useSavedJobIds,
  useSaveJob,
  useUnsaveJob,
} from '@/features/student/studentQueries';

const JOB_TYPE_LABEL = {
  'full-time': 'Full Time',
  internship: 'Internship',
  'part-time': 'Part Time',
};

export function StudentJobDetailsPage() {
  const { jobId } = useParams();
  const navigate = useNavigate();
  const { showToast } = useToast();
  const [matchModalOpen, setMatchModalOpen] = useState(false);

  const { data: job, isLoading, isError, refetch } = useJobDetails(jobId);
  const { data: applicationsData } = useMyApplications({ page: 1, limit: 100 });
  const { data: savedJobIds } = useSavedJobIds();
  const saveJob = useSaveJob();
  const unsaveJob = useUnsaveJob();
  const generateMatch = useGenerateJobMatch();

  const isSaved = (savedJobIds ?? []).includes(Number(jobId));

  const { data: relatedData } = useJobs(
    job ? { jobType: job.jobType, limit: 5 } : undefined
  );
  const relatedJobs = (relatedData?.jobs ?? []).filter(
    (relatedJob) => String(relatedJob.jobId) !== String(jobId)
  ).slice(0, 4);

  const {
    data: existingMatch,
    isLoading: isMatchLoading,
    error: matchFetchError,
  } = useJobMatch(jobId, { enabled: matchModalOpen });

  const matchNotYetGenerated = matchFetchError?.response?.status === 404;
  const needsAnalysis =
    matchFetchError?.response?.status === 409 || generateMatch.error?.response?.status === 409;
  const match = existingMatch ?? generateMatch.data;
  const isCheckingMatch = isMatchLoading || generateMatch.isPending;
  const matchFailed =
    (generateMatch.isError && !needsAnalysis) ||
    (Boolean(matchFetchError) && !matchNotYetGenerated && !needsAnalysis);

  const runGenerateMatch = useCallback(
    (id) => {
      generateMatch.mutate(id, {
        onError: (error) => {
          if (error.response?.status === 409) return;
          const message = error.response?.data?.message ?? 'Failed to check job match.';
          showToast({ variant: 'danger', title: 'Match check failed', description: message });
        },
      });
    },
    [generateMatch, showToast]
  );

  const hasAutoGeneratedMatch = useRef(false);

  useEffect(() => {
    if (!matchModalOpen) {
      hasAutoGeneratedMatch.current = false;
      return;
    }

    if (matchNotYetGenerated && !hasAutoGeneratedMatch.current) {
      hasAutoGeneratedMatch.current = true;
      runGenerateMatch(jobId);
    }
  }, [matchModalOpen, matchNotYetGenerated, jobId, runGenerateMatch]);

  function handleOpenMatch() {
    generateMatch.reset();
    setMatchModalOpen(true);
  }

  function handleCloseMatch(open) {
    setMatchModalOpen(open);
    if (!open) {
      generateMatch.reset();
    }
  }

  const hasApplied = (applicationsData?.applications ?? []).some(
    (application) => String(application.jobId) === String(jobId)
  );
  const isClosed = job?.status !== 'open';
  const isDeadlinePassed = job?.deadline && new Date(job.deadline) < new Date();

  function handleToggleSave() {
    if (isSaved) {
      unsaveJob.mutate(Number(jobId));
    } else {
      saveJob.mutate(Number(jobId));
    }
  }

  function handleShare() {
    navigator.clipboard
      .writeText(window.location.href)
      .then(() => showToast({ variant: 'success', title: 'Link copied to clipboard.' }))
      .catch(() => showToast({ variant: 'danger', title: 'Could not copy link.' }));
  }

  if (isLoading) {
    return (
      <div className="mx-auto flex max-w-6xl flex-col gap-6">
        <Skeleton className="h-4 w-16" />
        <div className="grid grid-cols-1 gap-6 lg:grid-cols-[1fr_320px]">
          <Card>
            <CardBody className="flex flex-col gap-4">
              <div className="flex items-start gap-4">
                <Skeleton className="h-14 w-14 shrink-0 rounded-[var(--radius-control)]" />
                <div className="flex-1">
                  <Skeleton className="h-6 w-1/2" />
                  <Skeleton className="mt-2 h-4 w-1/3" />
                </div>
              </div>
              <SkeletonText lines={6} className="mt-4" />
            </CardBody>
          </Card>
          <Card>
            <CardBody>
              <SkeletonText lines={5} />
            </CardBody>
          </Card>
        </div>
      </div>
    );
  }

  if (isError || !job) {
    return (
      <div className="mx-auto flex max-w-md flex-col items-center gap-3 py-16 text-center">
        <AlertTriangle className="h-8 w-8 text-text-muted" strokeWidth={1.5} aria-hidden="true" />
        <p className="text-sm font-semibold text-text">
          {isError ? 'Unable to load this job.' : 'Job not found.'}
        </p>
        {isError ? (
          <Button variant="outline" leftIcon={RefreshCcw} onClick={() => refetch()}>
            Try Again
          </Button>
        ) : (
          <Link to="/student/jobs">
            <Button variant="outline">Back to Find Jobs</Button>
          </Link>
        )}
      </div>
    );
  }

  const skills = parseJobSkills(job.requirements);

  return (
    <div className="mx-auto flex max-w-6xl flex-col gap-6">
      <motion.button
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 0.15 }}
        type="button"
        onClick={() => navigate(-1)}
        className="flex w-fit items-center gap-1 text-sm text-text-muted hover:text-text"
      >
        <ArrowLeft className="h-4 w-4" strokeWidth={1.75} />
        Back
      </motion.button>

      <motion.div
        initial={{ opacity: 0, y: 8 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.2 }}
        className="grid grid-cols-1 gap-6 lg:grid-cols-[1fr_320px] lg:items-start"
      >
        {/* LEFT / MAIN */}
        <div className="flex flex-col gap-6">
          <Card>
            <CardBody className="flex flex-col gap-4">
              <div className="flex flex-wrap items-start gap-4">
                <CompanyLogo name={job.Company?.name} logoPath={job.Company?.logoPath} size="lg" />
                <div className="min-w-0 flex-1">
                  <h1 className="text-xl font-semibold text-text">{job.title}</h1>
                  <p className="mt-0.5 text-sm text-text-muted">{job.Company?.name ?? 'Unknown company'}</p>

                  <div className="mt-3 flex flex-wrap items-center gap-x-4 gap-y-1 text-sm text-text-muted">
                    {job.location && (
                      <span className="flex items-center gap-1">
                        <MapPin className="h-4 w-4" strokeWidth={1.75} aria-hidden="true" />
                        {job.location}
                      </span>
                    )}
                    {job.createdAt && (
                      <span className="flex items-center gap-1">
                        <Calendar className="h-4 w-4" strokeWidth={1.75} aria-hidden="true" />
                        Posted {formatRelativeTime(job.createdAt)}
                      </span>
                    )}
                  </div>

                  <div className="mt-3 flex flex-wrap gap-2">
                    <Badge variant="default" icon={Briefcase}>
                      {JOB_TYPE_LABEL[job.jobType] ?? job.jobType}
                    </Badge>
                    {hasApplied && (
                      <Badge variant="success" icon={CheckCircle2}>
                        Already Applied
                      </Badge>
                    )}
                    {!hasApplied && (isClosed || isDeadlinePassed) && (
                      <Badge variant="danger">{isClosed ? 'Closed' : 'Deadline passed'}</Badge>
                    )}
                  </div>
                </div>
              </div>

              <div className="flex flex-wrap items-center gap-2 border-t border-border pt-4">
                <Button
                  variant="outline"
                  leftIcon={Heart}
                  onClick={handleToggleSave}
                  disabled={saveJob.isPending || unsaveJob.isPending}
                  className={isSaved ? 'text-danger' : undefined}
                >
                  {isSaved ? 'Saved' : 'Save Job'}
                </Button>
                <Button variant="outline" leftIcon={Sparkles} onClick={handleOpenMatch}>
                  Check Match
                </Button>
                <Button variant="outline" leftIcon={Share2} onClick={handleShare}>
                  Share
                </Button>
                {hasApplied ? (
                  <Badge variant="success" icon={CheckCircle2} className="ml-auto">
                    Applied
                  </Badge>
                ) : isClosed || isDeadlinePassed ? (
                  <Button className="ml-auto" disabled>
                    Apply Now
                  </Button>
                ) : (
                  <Link to={`/student/jobs/${jobId}/apply`} className="ml-auto">
                    <Button>Apply Now</Button>
                  </Link>
                )}
              </div>
            </CardBody>
          </Card>

          <Card>
            <CardBody className="flex flex-col gap-6">
              <div>
                <h2 className="text-sm font-semibold text-text">Job Description</h2>
                <p className="mt-2 whitespace-pre-line text-sm leading-relaxed text-text-muted">
                  {job.description}
                </p>
              </div>

              {job.requirements && (
                <div>
                  <h2 className="text-sm font-semibold text-text">Requirements</h2>
                  <p className="mt-2 whitespace-pre-line text-sm leading-relaxed text-text-muted">
                    {job.requirements}
                  </p>
                </div>
              )}

              {skills.length > 0 && (
                <div>
                  <h2 className="text-sm font-semibold text-text">Skills</h2>
                  <div className="mt-2 flex flex-wrap gap-1.5">
                    {skills.map((skill) => (
                      <span
                        key={skill}
                        className="inline-flex items-center rounded-full bg-surface-muted px-2.5 py-1 text-xs font-medium text-text-muted"
                      >
                        {skill}
                      </span>
                    ))}
                  </div>
                </div>
              )}
            </CardBody>
          </Card>

          {job.Company && (
            <Card>
              <CardBody className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
                <div className="flex items-center gap-3">
                  <CompanyLogo name={job.Company.name} logoPath={job.Company.logoPath} size="lg" />
                  <div>
                    <p className="text-sm font-semibold text-text">{job.Company.name}</p>
                    {job.location && (
                      <p className="mt-0.5 flex items-center gap-1 text-xs text-text-muted">
                        <MapPin className="h-3.5 w-3.5" strokeWidth={1.75} aria-hidden="true" />
                        {job.location}
                      </p>
                    )}
                    {job.Company.description && (
                      <p className="mt-1 max-w-md text-xs text-text-muted line-clamp-2">
                        {job.Company.description}
                      </p>
                    )}
                  </div>
                </div>
                <Link to={`/student/companies/${job.Company.companyId}`} className="shrink-0">
                  <Button variant="outline" leftIcon={Building2}>
                    View Company
                  </Button>
                </Link>
              </CardBody>
            </Card>
          )}
        </div>

        {/* RIGHT / SUMMARY */}
        <div className="flex flex-col gap-6">
          <Card>
            <CardBody className="flex flex-col gap-4">
              <h2 className="text-sm font-semibold text-text">Job Overview</h2>

              <div className="flex flex-col gap-3 text-sm">
                <div className="flex items-center justify-between gap-2">
                  <span className="text-text-muted">Job Type</span>
                  <span className="font-medium text-text">{JOB_TYPE_LABEL[job.jobType] ?? job.jobType}</span>
                </div>
                {job.location && (
                  <div className="flex items-center justify-between gap-2">
                    <span className="text-text-muted">Location</span>
                    <span className="font-medium text-text">{job.location}</span>
                  </div>
                )}
                {job.deadline && (
                  <div className="flex items-center justify-between gap-2">
                    <span className="text-text-muted">Apply By</span>
                    <span className="font-medium text-text">{new Date(job.deadline).toLocaleDateString()}</span>
                  </div>
                )}
                {job.createdAt && (
                  <div className="flex items-center justify-between gap-2">
                    <span className="text-text-muted">Posted</span>
                    <span className="font-medium text-text">{formatRelativeTime(job.createdAt)}</span>
                  </div>
                )}
              </div>

              <div className="flex flex-col gap-2 border-t border-border pt-4">
                {hasApplied ? (
                  <Badge variant="success" icon={CheckCircle2} className="w-fit">
                    Applied
                  </Badge>
                ) : isClosed || isDeadlinePassed ? (
                  <Button disabled>Apply Now</Button>
                ) : (
                  <Link to={`/student/jobs/${jobId}/apply`}>
                    <Button className="w-full">Apply Now</Button>
                  </Link>
                )}
                <Button
                  variant="outline"
                  leftIcon={Heart}
                  onClick={handleToggleSave}
                  disabled={saveJob.isPending || unsaveJob.isPending}
                  className={isSaved ? 'text-danger' : undefined}
                >
                  {isSaved ? 'Saved' : 'Save Job'}
                </Button>
              </div>
            </CardBody>
          </Card>
        </div>
      </motion.div>

      {relatedJobs.length > 0 && (
        <div className="flex flex-col gap-4">
          <h2 className="text-lg font-semibold text-text">You may also like</h2>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
            {relatedJobs.map((relatedJob) => (
              <JobCard
                key={relatedJob.jobId}
                job={relatedJob}
                hasApplied={(applicationsData?.applications ?? []).some(
                  (application) => String(application.jobId) === String(relatedJob.jobId)
                )}
                isSaved={(savedJobIds ?? []).includes(relatedJob.jobId)}
                onToggleSave={(id, saved) => (saved ? unsaveJob.mutate(id) : saveJob.mutate(id))}
                isSaveLoading={saveJob.isPending || unsaveJob.isPending}
              />
            ))}
          </div>
        </div>
      )}

      <JobMatchModal
        open={matchModalOpen}
        onOpenChange={handleCloseMatch}
        match={match}
        isLoading={isCheckingMatch}
        isError={matchFailed}
        needsAnalysis={needsAnalysis}
        onRetry={() => runGenerateMatch(jobId)}
      />
    </div>
  );
}
